export const invoice =
{
  "document_type": "invoice",
  "amount": 0,
  "amount_change": 0,
  "vatamount": 0,
  "amountexvat": 0,
  "currency": "EUR",
  "date": "2020-07-19T00:00:00",
  "purchasedate": "2020-07-19",
  "purchasetime": "00:00:00",
  "vatitems": [],
  "vat_context": "",
  "lines": [
    {
      "description": "",
      "lineitems": [
        {
          "title": "351421 Corsair DDR4 Vengeance LPX 2x8GB 3200 C16 Geheugen 120 mnd. 1",
          "description": "",
          "amount": 6490,
          "amount_each": 6490,
          "amount_ex_vat": 6490,
          "vat_amount": 0,
          "vat_percentage": 0,
          "quantity": 1,
          "sku": "",
          "vat_code": ""
        },
        {
          "title": "20153 Verzenden binnen Nederland 1\n20133 Webshopkosten iDEAL 1",
          "description": "",
          "amount": 395,
          "amount_each": 395,
          "amount_ex_vat": 395,
          "vat_amount": 0,
          "vat_percentage": 0,
          "quantity": 1,
          "sku": "",
          "vat_code": ""
        },
        {
          "title": "2100024118526 21.0",
          "description": "",
          "amount": 1195,
          "amount_each": 5690,
          "amount_ex_vat": 1195,
          "vat_amount": 0,
          "vat_percentage": 0,
          "quantity": 1,
          "sku": "",
          "vat_code": ""
        }
      ]
    }
  ],
  "paymentmethod": "bank",
  "payment_auth_code": "",
  "payment_card_number": "",
  "payment_card_account_number": "",
  "payment_card_bank": "",
  "payment_card_issuer": "",
  "payment_due_date": "",
  "terminal_number": "",
  "document_subject": "",
  "package_number": "",
  "invoice_number": "M000938300",
  "invoice_type": "invoice",
  "receipt_number": "M000938300",
  "shop_number": "",
  "transaction_number": "",
  "transaction_reference": "",
  "order_number": "",
  "table_number": "",
  "table_group": "",
  "server": "",
  "merchant_name": "Megekko",
  "merchant_id": "",
  "merchant_coc_number": "20093810",
  "merchant_vat_number": "NL808060016B01",
  "merchant_bank_account_number": "NL60INGB0007948866",
  "merchant_bank_account_number_bic": "",
  "merchant_chain_liability_bank_account_number": "",
  "merchant_bank_domestic_account_number": "0007948866",
  "merchant_bank_domestic_bank_code": "INGB",
  "merchant_website": "http://www.megekko.nl",
  "merchant_email": "info@megekko.nl",
  "merchant_address": "Spinveld 8",
  "merchant_street_name": "Spinveld",
  "merchant_house_number": "8",
  "merchant_zipcode": "4815 HS",
  "merchant_city": "Breda",
  "merchant_municipality": "",
  "merchant_province": "",
  "merchant_country": "",
  "merchant_country_code": "NL",
  "merchant_phone": "",
  "merchant_main_activity_code": "",
  "customer_name": "Ilona Rus",
  "customer_number": "10267695",
  "customer_reference": "",
  "customer_address": "Herehof 9",
  "customer_street_name": "Herehof",
  "customer_house_number": "9",
  "customer_zipcode": "9725 AZ",
  "customer_city": "Groningen",
  "customer_municipality": "",
  "customer_province": "",
  "customer_country": "",
  "customer_phone": "",
  "customer_vat_number": "",
  "customer_coc_number": "",
  "customer_bank_account_number": "",
  "customer_bank_account_number_bic": "",
  "customer_website": "",
  "customer_email": "",
  "payment_slip_code": "",
  "payment_slip_reference_number": "",
  "payment_slip_customer_number": "",
  "matched_keywords": null,
  "matched_lineitems": null,
  "matched_purchase_order_id": "",
  "barcodes": null,
  "hash": "",
  "hash_duplicate": false,
  "raw_text": " FACTUUR\n Datum: 19-07-2020\nIlona Rus Factuurnummer: M000938300\nHerehof 9 Klantnummer : 10267695\n9725az Groningen Betaalmethode: Ideal\nNederland\n\n\nARTIKEL GARANTIE AANTAL PRIJS (in BTW) TOTAAL\n\n351421 Corsair DDR4 Vengeance LPX 2x8GB 3200 C16 Geheugen 120 mnd. 1 64.90 64.90\n20153 Verzenden binnen Nederland 1 3.95 3.95\n20133 Webshopkosten iDEAL 1\n Webshoporder: ME1807200355\n\n\n\n\n FACTUURCODE EXCL. BTW BTW-TARIEF BTW-BEDRAG TOTAAL\n 0.00 0.0 Euro 68.85\n 0.00 9.0 0.00 AANTAL ARTIKELEN\n2100024118526 56.90 21.0 11.95 3\n\nMEGEKKO B.V. KVK Breda 20093810 - Rekeningnr: NL 60 INGB 0007 9488 66 - BTW NL808060016B01\nServicedesk: Spinveld 8, 4815 HS Breda, Nederland - www.megekko.nl - info@megekko.nl 1\nKijk op www.megekko.nl/info/retouren voor onze retourprocedure. Op deze factuur zijn onze algemene voorwaarden van toepassing.\n"
}